
spring:
  datasource:
    sybase:
      jdbc-url: jdbc:sybase:Tds:sybase-host:5000/DBNAME
      username: syb_user
      password: syb_pass
      driver-class-name: com.sybase.jdbc4.jdbc.SybDriver
  data:
    mongodb:
      uri: mongodb://localhost:27017/syncdb
